
 langs:
   -
     lang:
     title: Auf Deutsch
#   -
#     lang: en
#     title: In English
   -
     lang: fr
     title: en français
#   -
#     lang: es
#     title: en español
#   -
#     lang: pl
#     title: po polsku